[workspace]

members = [
    "crane",
    "elves",
    "forest",
    "ioutils",
    "rock_paper_scissors",
    "rucksacks",
    "day_1",
    "day_2",
    "day_3",
    "day_4",
    "day_5",
    "day_6",
    "day_7",
    "day_8",
    "day_9",
]
