[workspace]

members = [
    "elves",
    "rock_paper_scissors",
    "rucksacks",
    "ioutils",
    "crane",
    "day_1",
    "day_2",
    "day_3",
    "day_4",
    "day_5",
    "day_6",
    "day_7",
]
